// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CATestContactList;
using CATestContactList.Models;
using Microsoft.Rest;

namespace CATestContactList
{
    public static partial class ContactsExtensions
    {
        /// <param name='operations'>
        /// Reference to the CATestContactList.IContacts.
        /// </param>
        public static IList<Contact> GetContacts(this IContacts operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContacts)s).GetContactsAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the CATestContactList.IContacts.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Contact>> GetContactsAsync(this IContacts operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<CATestContactList.Models.Contact>> result = await operations.GetContactsWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
